version: 2
jobs:
  build:
    working_directory: ~/ng2-facebook-sdk-example/
    docker:
      - image: node:7
    branches:
      - only:
        - master
    steps:
      - checkout
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
           - ~/ng2-facebook-sdk/node_modules/
      - run: npm run ng -- build --prod
      - run: cd ../
