version: 2
jobs:
  build:
    working_directory: ~/ng2-facebook-sdk-example/
    docker:
      - image: node:7
    branches:
      - only:
        - master
    steps:
      - checkout
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
           - ~/ng2-facebook-sdk/node_modules/
      - run: npm run build:prod
      - run: git checkout gh-pages
      - run: mv dist/* .
      - run: rm -rf dist node_modules
      - run: git config --global user.name="ZM Bot"
      - run: git config --global user.email="ibby93+zmbot@gmail.com"
      - run: git add .
      - run: git commit -am "Automated build"
      - add_ssh_keys
      - run: git push origin gh-pages
